Index: test/src/module2/homeTask3/errorNotInt/Main.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.BaseRevisionTextPatchEP
<+>package module2.homeTask3.errorNotInt;\r\n\r\nimport java.util.InputMismatchException;\r\nimport java.util.Scanner;\r\n\r\npublic class Main {\r\n    public static void main(String[] args) throws NumberFormatException {\r\n        System.out.println(\"Input the number : \");\r\n        Scanner sc = new Scanner(System.in);\r\n        try {\r\n            int a = Integer.parseInt(sc.next());\r\n            Calculate.check(a);\r\n        } catch (NumberFormatException e) {\r\n            System.err.println(e.getMessage());;\r\n        }\r\n\r\n    }\r\n}\r\n
===================================================================
diff --git a/test/src/module2/homeTask3/errorNotInt/Main.java b/test/src/module2/homeTask3/errorNotInt/Main.java
--- a/test/src/module2/homeTask3/errorNotInt/Main.java	
+++ b/test/src/module2/homeTask3/errorNotInt/Main.java	
@@ -1,4 +1,4 @@
-package module2.homeTask3.errorNotInt;
+package Module2.homeTask3.errorNotInt;
 
 import java.util.InputMismatchException;
 import java.util.Scanner;
@@ -9,7 +9,7 @@
         Scanner sc = new Scanner(System.in);
         try {
             int a = Integer.parseInt(sc.next());
-            Calculate.check(a);
+            module2.homeTask3.errorNotInt.Calculate.check(a);
         } catch (NumberFormatException e) {
             System.err.println(e.getMessage());;
         }
Index: test/src/module2/homeTask3/errorSumInt/Main.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.BaseRevisionTextPatchEP
<+>package module2.homeTask3.errorSumInt;\r\n\r\nimport module2.homeTask3.errorNotInt.Calculate;\r\n\r\nimport java.util.InputMismatchException;\r\n\r\nimport java.util.Scanner;\r\n\r\npublic class Main {\r\n    public static void main(String[] args) throws NumberFormatException {\r\n        int a;\r\n        int b;\r\n        System.out.println(\"Input the two number : \");\r\n        Scanner sc = new Scanner(System.in);\r\n        try {\r\n            a = Integer.parseInt(sc.next());\r\n            b = Integer.parseInt(sc.next());\r\n            Sum.check(a, b);\r\n        } catch (NumberFormatException e) {\r\n            System.err.println(e.getMessage());\r\n        }\r\n\r\n    }\r\n}\r\n
===================================================================
diff --git a/test/src/module2/homeTask3/errorSumInt/Main.java b/test/src/module2/homeTask3/errorSumInt/Main.java
--- a/test/src/module2/homeTask3/errorSumInt/Main.java	
+++ b/test/src/module2/homeTask3/errorSumInt/Main.java	
@@ -15,7 +15,7 @@
         try {
             a = Integer.parseInt(sc.next());
             b = Integer.parseInt(sc.next());
-            Sum.check(a, b);
+            module2.homeTask3.errorSumInt.Sum.check(a, b);
         } catch (NumberFormatException e) {
             System.err.println(e.getMessage());
         }
